### ISSUE TITLE
Issues Loading TMX FIles

### ISSUE THREAD

**Issue by imeidopf** [bitcraft/pytmx#145]
Having an issue loading my tmx files with this module. Getting this error:
```pygame 2.0.1 (SDL 2.0.14, Python 3.9.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\path\to\python\file\readXML.py", line 2, in <module>
    tiled_map = pytmx.TiledMap('home.tmx')
  File "C:\path\to\python\file\AppData\Local\Programs\Python\Python39\lib\site-packages\pytmx\pytmx.py", line 370, in 
__init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "C:\path\to\python\file\AppData\Local\Programs\Python\Python39\lib\site-packages\pytmx\pytmx.py", line 415, in 
parse_xml
    self.add_tileset(TiledTileset(self, subnode))
  File "C:\path\to\python\file\AppData\Local\Programs\Python\Python39\lib\site-packages\pytmx\pytmx.py", line 866, in 
__init__
    self.parse_xml(node)
  File "C:\path\to\python\file\Local\Programs\Python\Python39\lib\site-packages\pytmx\pytmx.py", line 968, in 
parse_xml
    self.width = int(image_node.get('width'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
This is my python file:

```python
import pytmx
tiled_map = pytmx.TiledMap('home.tmx')
```
Here is the tmx:
```xml
<?xml version="1.0" encoding="utf-8"?>
<map version="1.0" orientation="orthogonal" width="10" height="10" tilewidth="32" tileheight="32">
    <tileset firstgid="1" name="map_10" tilewidth="32" tileheight="32">
        <image source="../drawable/map_10.png" />
    </tileset>
    <tileset firstgid="65" name="map_18" tilewidth="32" tileheight="32">
        <image source="../drawable/map_18.png" />
    </tileset>
    <tileset firstgid="129" name="map_27" tilewidth="32" tileheight="32">
        <image source="../drawable/map_27.png" />
    </tileset>
    <tileset firstgid="193" name="map_35" tilewidth="32" tileheight="32">
        <image source="../drawable/map_35.png" />
    </tileset>
    <tileset firstgid="257" name="map_12" tilewidth="32" tileheight="32">
        <image source="../drawable/map_12.png" />
    </tileset>
    <tileset firstgid="321" name="map_9" tilewidth="32" tileheight="32">
        <image source="../drawable/map_9.png" />
    </tileset>
    <tileset firstgid="385" name="map_15" tilewidth="32" tileheight="32">
        <image source="../drawable/map_15.png" />
    </tileset>
    <tileset firstgid="449" name="map_3" tilewidth="32" tileheight="32">
        <image source="../drawable/map_3.png" />
    </tileset>
    <tileset firstgid="513" name="map_22" tilewidth="32" tileheight="32">
        <image source="../drawable/map_22.png" />
    </tileset>
    <tileset firstgid="577" name="map_7" tilewidth="32" tileheight="32">
        <image source="../drawable/map_7.png" />
    </tileset>
    <tileset firstgid="641" name="map_25" tilewidth="32" tileheight="32">
        <image source="../drawable/map_25.png" />
    </tileset>
    <tileset firstgid="705" name="map_11" tilewidth="32" tileheight="32">
        <image source="../drawable/map_11.png" />
    </tileset>
    <tileset firstgid="769" name="map_24" tilewidth="32" tileheight="32">
        <image source="../drawable/map_24.png" />
    </tileset>
    <tileset firstgid="833" name="map_2" tilewidth="32" tileheight="32">
        <image source="../drawable/map_2.png" />
    </tileset>
    <tileset firstgid="897" name="map_0" tilewidth="32" tileheight="32">
        <image source="../drawable/map_0.png" />
    </tileset>
    <tileset firstgid="961" name="map_1" tilewidth="32" tileheight="32">
        <image source="../drawable/map_1.png" />
    </tileset>
    <tileset firstgid="1025" name="map_21" tilewidth="32" tileheight="32">
        <image source="../drawable/map_21.png" />
    </tileset>
    <layer name="Ground" width="10" height="10">
        <data encoding="base64" compression="zlib"> eJwTZWBgECUSixHAMHXiBDBMnRQBTIk6fyAOhOJgPOq6gPgeFHcjqRMjQp0Y1D/I6gKAOAiKQ6BiIDUSSFgKjY+MATl2D/E=
</data>
    </layer>
    <layer name="Objects" width="10" height="10">
        <data encoding="base64" compression="zlib"> eJxjYCAeKDAyMEgwIvgwNiszplpJoNxqIJZjgrBNgWJ2QDwfSb8okN0CxFuBWBqozgeIzRgQGAbEGBmIAhOI9MdEKP4JNFcTiBWAbCUGCBsZxKLxJwLdN4kJU108Eh8kZw+kDzJB+OeZiHQUFAAAnn0MMg==
</data>
    </layer>
    <layer name="Above" width="10" height="10">
        <data encoding="base64" compression="zlib"> eJxjYCAeODITp24lkjp8epDV3SdSHSF7JxCpDhnoMhJvrxcWtdjUybMQ4RAsAADc1wdL
</data>
    </layer>
    <layer name="Walkable" width="10" height="10">
        <data encoding="base64" compression="zlib"> eJxLYWZgSBnkmBAgVi0uc3Hx0c2jhjqYOC6/AgDNhhwr
</data>
    </layer>
    <objectgroup name="mapevents">
        <object name="entrance" type="mapchange" x="96" y="288" width="32" height="32">
            <properties>
                <property name="map" value="crossglen" />
                <property name="place" value="home" />
            </properties>
        </object>
        <object name="rest" type="rest" x="32" y="128" width="32" height="32" />
        <object name="startitems2" type="container" x="256" y="256" width="32" height="32" />
        <object name="grownfood_init" type="script" x="192" y="128" width="32" height="64" />
    </objectgroup>
    <objectgroup name="keys">
        <object name="andor:1" type="key" x="0" y="288" width="320" height="32">
            <properties>
                <property name="phrase" value="keyarea_andor1" />
                <property name="requireId" value="andor" />
                <property name="requireType" value="questProgress" />
                <property name="requireValue" value="1" />
            </properties>
        </object>
    </objectgroup>
    <objectgroup name="spawn">
        <object name="mikhail" type="spawn" x="224" y="128" width="32" height="32">
            <properties>
                <property name="spawngroup" value="mikhail" />
            </properties>
        </object>
    </objectgroup>
</map>
```

Am I missing something?

**Comment by bitcraft** [comment]
thanks for posting the tmx file, thats really helpful.  it looks like the format has changed some and is not including the tileset image dimensions

```xml
<tileset firstgid="513" name="map_22" tilewidth="32" tileheight="32">
    <image source="../drawable/map_22.png" />
</tileset>
```

An older map image looks like this:
```xml
<tileset firstgid="89" name="furniture" tilewidth="16" tileheight="16" tilecount="72" columns="12">
    <image source="../gfx/tilesets/furniture.png" width="192" height="96"/>
</tileset>
 ```
 
 so...nothing you did wrong but the code cannot handle this newer map.  if you are brave, you can edit the xml and add the pixel width/height as a work around (as im my example).  should be simple and i doubt you will lose those changes when you save it again.
 
 the code here https://github.com/bitcraft/pytmx/blob/master/pytmx/pytmx.py#L967 will need to be updated to get the dimensions of the image by from the image loader or some other means.

**Comment by imeidopf** [comment]
@bitcraft Adding width and height to my tmx files did the trick. Thank you for the response!

**Comment by bitcraft** [comment]
Glad it worked out for you!  I'm going to reopen this as a reminder to fix it though.

**Comment by imeidopf** [comment]
@bitcraft , do you have a method to get in contact? I have a separate questions.

**Comment by bitcraft** [comment]
im "bitcraft" in the pygame discord.  look me up and send a dm would be fine.

**Comment by bitcraft** [comment]
addressed https://github.com/bitcraft/pytmx/commit/8fbb477d0b1b1185fb3f0c60d016f6f7b2d785dc
