### ISSUE TITLE
Getting: `pygame.error: Parameter 'surface' is invalid`

### ISSUE THREAD

**Issue by jhutar** [bitcraft/pytmx#192]
Hello and thank you for great library! Not sure what am I doing wrong, but I'm getting this traceback:

```
Traceback (most recent call last):
  File "/home/jhutar/Checkouts/CatWars/./reproducer.py", line 8, in <module>
    tmxdata = pytmx.util_pygame.load_pygame("catwars/assets/tileset/CatWars-level1.tmx")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhutar/.local/lib/python3.12/site-packages/pytmx/util_pygame.py", line 183, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhutar/.local/lib/python3.12/site-packages/pytmx/pytmx.py", line 549, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "/home/jhutar/.local/lib/python3.12/site-packages/pytmx/pytmx.py", line 633, in parse_xml
    self.reload_images()
  File "/home/jhutar/.local/lib/python3.12/site-packages/pytmx/pytmx.py", line 686, in reload_images
    self.images[gid] = loader(rect, flags)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/jhutar/.local/lib/python3.12/site-packages/pytmx/util_pygame.py", line 146, in load_image
    tile = smart_convert(tile, colorkey, pixelalpha)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhutar/.local/lib/python3.12/site-packages/pytmx/util_pygame.py", line 102, in smart_convert
    tile = original.convert()
           ^^^^^^^^^^^^^^^^^^
pygame.error: Parameter 'surface' is invalid
```

Code I'm using is:

```
#!/usr/bin/env python
import pygame
import pytmx
import sys

pygame.init()

tmxdata = pytmx.util_pygame.load_pygame("catwars/assets/tileset/CatWars-level1.tmx")
world_size = (
    tmxdata.width * tmxdata.tilewidth,
    tmxdata.height * tmxdata.tileheight,
)

clock = pygame.time.Clock()
screen = pygame.display.set_mode(world_size)

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    for layer in tmxdata:
        if layer.name == "ground":
            for tile in layer.tiles():
                x_top_left = tile[0] * tmxdata.tilewidth
                y_top_left = tile[1] * tmxdata.tileheight
                screen.blit(tile[2], (x_top_left, y_top_left))

    pygame.display.update()

    clock.tick(30)
```

It is possible to overcome that error if I do this workaround:

```
$ diff -u ~/.local/lib/python3.12/site-packages/pytmx/util_pygame.py{.ORIG,}
--- .../.local/lib/python3.12/site-packages/pytmx/util_pygame.py.ORIG	2024-09-16 21:27:27.803974724 +0200
+++ .../.local/lib/python3.12/site-packages/pytmx/util_pygame.py	2024-09-16 21:29:08.561690006 +0200
@@ -99,7 +99,10 @@
 
         # there are no transparent pixels in the image
         if px == tile_size[0] * tile_size[1]:
-            tile = original.convert()
+            try:
+                tile = original.convert()
+            except pygame.error:
+                tile = original
 
         # there are transparent pixels, and set for perpixel alpha
         elif pixelalpha:
```

tmx and png data are here:

* Tileset PNG: https://github.com/jhutar/CatWars/blob/770bbae09c70dc70fa2f63032a74f1ebba060f37/catwars/assets/tileset/CatWars-tileset.png
* Tileset TSX: https://github.com/jhutar/CatWars/blob/770bbae09c70dc70fa2f63032a74f1ebba060f37/catwars/assets/tileset/CatWars-tileset.xcf
* Map TMX: https://github.com/jhutar/CatWars/blob/770bbae09c70dc70fa2f63032a74f1ebba060f37/catwars/assets/tileset/CatWars-level1.tmx

Versions I'm using:

```
$ python --version
Python 3.12.5
$ rpm -q python3-pygame
python3-pygame-2.6.0-1.fc40.x86_64
$ pip freeze | grep -i pytmx
PyTMX==3.32
```

What am I doing wrong please?

**Comment by agaricus-campestris** [comment]
I have the same problem with 
`pygame 2.6.1 (SDL 2.32.68, Python 3.14.5)`
but not with 
`pygame-ce 2.5.6 (SDL 2.32.10, Python 3.11.2)`

Here is my messy code :

```
#!/usr/bin/env python
import os, sys
parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.append(parent_dir)
import csv, logging, time, datetime, subprocess, signal, random, logging_config
import pygame
from pygame import mixer
from pathlib import Path
import midifile
logger = logging.getLogger("karaokeke.play2")

currentDirectory="/home/kara/karaokeke"

# FIXME maybe this needs to be refactored so we could use it without main.py
if len(sys.argv) > 2:
    print("Usage: python main.py <karaoke_file.kar>")
    sys.exit(1)

karaoke_file = sys.argv[1]

def playKara(karaoke_file):
    global screenx # la width largeur
    global screeny # la height hauteur
    global screen
    global font
    global purple
    global white
    global red
    global yellow
    global green
    global active_text_color
    global base_text_color
    global clock
    global font_fade
    global donePlaying

    # FIXME do I need to change buffer (2048) to 128 to follow qjackctl conf ?
    # pygame.mixer.pre_init(44100, -16, 2, 2048)
    # FIXME NEW faire tous les pygames init au début du programme

    pygame.mixer.pre_init(frequency=44100, buffer=64)
    pygame.init()
    pygame.mixer.init()
    # pygame.mixer.init(devicename='/dev/shm/jack-1000/default/jack_0')
    infoDisplay = pygame.display.Info()
    screenx = 1600
    screeny = 1000
    logger.debug(f"SCREENX DISPLAY {screenx} --- SCREENY {screeny}")
    screen = pygame.display.set_mode((screenx, screeny))

    font = pygame.font.Font(None, 60)

    purple = (100, 100, 250, 0)
    white = (250, 250, 250, 0)
    yellow = (224, 207, 19, 1)
    green = (68, 254, 68, 1)
    red = (255, 34, 34, 1)

    active_text_color = purple
    base_text_color = white

    # FIXME centrer : 
    # https://overflow.ducks.party/questions/23982907/how-to-center-text-in-pygame
    # screen.fill(green) # fill screen with yellow greenish background

    # logger.debug(f"initPygame lancé ! purple {purple}, white : {white}, SCREEN : {screen}, screnX : {screenx}, screnY : {screeny}, FONT : {font}, ACTIVE_text_color {active_text_color}, BASE_text_color : {base_text_color} ")
    pygame.mouse.set_visible(False) # Hide cursor here
    pygame.display.flip() # FIXME on dirait ça sert à R ?
    # Laissons les z'humains se reposer de leurs n'émotions
    time.sleep(10)

    pygame.display.set_caption(karaoke_file)
    start = datetime.datetime.now()
    done = False

    m = midifile.midifile()
    m.load_file(karaoke_file)

    # Find the earliest note time - this is when audio actually starts
    # (MIDI files can have silence at the beginning before the first note)
    earliest_note_sec = 0.0
    if m.notes:
        valid_notes = [n[5] for n in m.notes if n[5] >= 0]
        if valid_notes:
            earliest_note_sec = min(valid_notes)

    pygame.mixer.music.set_volume(0.8)
    pygame.mixer.music.load(karaoke_file)

    logger.debug("=" * 60)
    logger.debug("Audio loaded, starting playback...")
    logger.debug(f"BPM from file: {m.bpm}")
    logger.debug(f"Microseconds per quarter note: {m.microsecondsperquarternote}")
    logger.debug(f"First 10 syllables: {m.karsyl[:10]}")
    logger.debug(f"First 10 kartimes: {[f'{t:.2f}' for t in m.kartimes[:10]]}")
    if len(m.kartimes) > 0:
        logger.debug(f"First lyric expected at: {m.kartimes[0]:.2f}s")
    logger.debug("=" * 60)

    timidity_proc = pygame.mixer.music.play(0, 0)
    pygame.time.wait(50) # FIXME c quoi ce wait ? de base c'est 50
    # on dirait que ce wait permet de pas lancer la track hyper vite et 
    # empêche de couper le début du morceau

    logger.info("Playing ｡：ﾟ(｡ﾉω＼｡)ﾟ･｡")

    done = False

    dt = 0.0
    first_lyric_shown = False
    last_debug_time = -1

    if not m.karfile:
        logger.info("This is not a karaoke file. I'll just play it")
        while pygame.mixer.music.get_busy():
            time.sleep(1)
        sys.exit(0)

    buffer_samples = 2048
    freq, size, channels = pygame.mixer.get_init()

    # Ça c'est pour afficher les paroles
    # il faut que j'appelle un reader de fifo voir si ya startswith num/track
    # ou nagui, ou dring, ou fumée, etc FIXME NEW
    while pygame.mixer.music.get_busy() and not done:

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                done = True
            # FIXME ? if event.type == pygame.mixer.music.stop ?

        buffer_delay_ms = (buffer_samples * 1000) / (freq * channels)
        buffer_delay_sec = buffer_delay_ms / 1000.0

        raw_pos_sec = pygame.mixer.music.get_pos() / 1000.0
        song_time = raw_pos_sec + earliest_note_sec - buffer_delay_sec

        m.update_karaoke(song_time)

        for iline in range(3):
            l = font.size(m.karlinea[iline] + m.karlineb[iline])[0]
            x0a = screenx / 2 - l / 2.0
            line_a = font.render(m.karlinea[iline], 0, active_text_color)
            line_b = font.render(m.karlineb[iline], 0, base_text_color)
            rect_a = screen.blit(line_a, [x0a, 80 + iline * 60])
            x0b = x0a + rect_a.width
            rect_b = screen.blit(line_b, [x0b, 80 + iline * 60])

        # .flip same as .update 
        pygame.display.flip()
        # remplie le fond avec du noir pour écraser les paroles d'avant
        screen.fill(0)

        # attend légèrement avant d'afficher la suite des paroles 
        time.sleep(0.1)

    # Fin de playKara

playKara(karaoke_file)
```

**Comment by agaricus-campestris** [comment]
Also here is my error :
```
pygame.error: Parameter 'surface' is invalid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tools/play2.py", line 159, in <module>
    playKara(karaoke_file)
    ~~~~~~~~^^^^^^^^^^^^^^
  File "./tools/play2.py", line 145, in playKara
    rect_a = screen.blit(line_a, [x0a, 80 + iline * 60])
SystemError: <method 'blit' of 'pygame.surface.Surface' objects> returned a result with an exception set
fish: Job 1, 'python3 ./tools/play2.py' terminated by signal SIGSEGV (Address boundary error)
```

EDIT : sorry for the noise, I thought I was inside pygame repository, I found this issue searching for `pygame.error: Parameter 'surface' is invalid`, downgrading helped, I hope this feedback will also help
