### ISSUE TITLE
ValueError in load_pygame

### ISSUE THREAD

**Issue by freeDom-** [bitcraft/PyTMX#63]
There seems to be a problem with floating point numbers in the object layers `x`, `y`, `width` or `height` attribute.. The error disappeared after I manually rounded all of the floats inside the tmx-file:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\pytmx\util_pygame.py", line 112, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 258, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 286, in parse_xml
    self.add_layer(TiledObjectGroup(self, subnode))
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 1013, in __init__
    self.parse_xml(node)
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 1023, in parse_xml
    for child in node.findall('object'))
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 1023, in <genexpr>
    for child in node.findall('object'))
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 945, in __init__
    self.parse_xml(node)
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 965, in parse_xml
    self.set_properties(node)
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 177, in set_properties
    self.cast_and_set_attributes_from_node_items(node.items())
  File "C:\Python35\lib\site-packages\pytmx\pytmx.py", line 153, in cast_and_set_attributes_from_node_items
    casted_value = types[key](value)
ValueError: invalid literal for int() with base 10: '80.25'

**Comment by bitcraft** [comment]
Thanks for letting me know about this issue.  I'll see what I can do.

**Comment by bitcraft** [comment]
I've fixed this in the latest commit.  Feel free to update via pip or this repo and let me know if this fixes your issue.  Thanks again!

**Comment by freeDom-** [comment]
Working like a charm! Thx for the fast fix and generally for your great work with the packages!
