### ISSUE TITLE
Map Version cast to Float

### ISSUE THREAD

**Issue by emanual4real** [bitcraft/PyTMX#81]
Forgive me if this is stupid, I'm a noob to PyTMX.  I created a tmx map and I'm trying to load the map and I get the below error.  For some reason it's trying to convert the XML map version to a float.  I'd appreciate any help.  Thanks.

Manny

```
import pytmx
from pytmx.util_pygame import load_pygame

tmxdata = load_pygame('map.tmx')
```

```
Traceback (most recent call last):
  File "c:/Users/Eman-Win10/Desktop/Python Examples/unnamed_game - Copy/example.py", line 4, in <module>
    tmxdata = load_pygame('map.tmx')
  File "C:\Python36-32\lib\site-packages\pytmx\util_pygame.py", line 116, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
  File "C:\Python36-32\lib\site-packages\pytmx\pytmx.py", line 285, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "C:\Python36-32\lib\site-packages\pytmx\pytmx.py", line 309, in parse_xml
    self._set_properties(node)
  File "C:\Python36-32\lib\site-packages\pytmx\pytmx.py", line 295, in _set_properties
    TiledElement._set_properties(self, node)
  File "C:\Python36-32\lib\site-packages\pytmx\pytmx.py", line 203, in _set_properties
    self._cast_and_set_attributes_from_node_items(node.items())
  File "C:\Python36-32\lib\site-packages\pytmx\pytmx.py", line 166, in _cast_and_set_attributes_from_node_items
    casted_value = types[key](value)
ValueError: could not convert string to float: '2017.05.16'
```

**Comment by bitcraft** [comment]
No worries.  What is the name of the "2017.05.16" value?

**Comment by bitcraft** [comment]
It looks like that is because the version is not a number.  You can change it to a float or integer, or wait until I get a fix for it.

If anyone has any objections, I can change the version to a string.  I don't think it is really used much.

**Comment by emanual4real** [comment]
It is "version" in the "map" tag.  I changed the version to a float and I no longer have the error.  Thanks!
