### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by GoldsteinE** [bitcraft/PyTMX#94]
For simple TMX-file (attached) raises ValueError when trying to do pytmx.TiledMap('intro.tmx'). Some data:
```python
>>> sys.version
'3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]'
>>> pytmx.__version__
3.21.3
>>> pytmx.TiledMap('intro.tmx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Documents\Projects\hateyou\venv\lib\site-packages\pytmx\pytmx.py", line 300, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "D:\Documents\Projects\hateyou\venv\lib\site-packages\pytmx\pytmx.py", line 331, in parse_xml
    self.add_layer(TiledTileLayer(self, subnode))
  File "D:\Documents\Projects\hateyou\venv\lib\site-packages\pytmx\pytmx.py", line 886, in __init__
    self.parse_xml(node)
  File "D:\Documents\Projects\hateyou\venv\lib\site-packages\pytmx\pytmx.py", line 997, in parse_xml
    self.data[y][x] = reg(*decode_gid(next(next_gid)))
ValueError: invalid literal for int() with base 10: ''
```

Windows 10 x64.

**UPD:** Problem is in infinite maps.

[maps.zip](https://github.com/bitcraft/PyTMX/files/1492397/maps.zip)

**Comment by bitcraft** [comment]
Thanks for the report and for the test map.  Pytmx is actually pretty behind Tiled at the moment.  Is the attached map using infinite bounds?  I've scheduled time tomorrow to work on pytmx....your timing is really good. 
🙂

**Comment by GoldsteinE** [comment]
Yes, infinite bounds. Infinite maps are split in "chunks" and pytmx doesn't see it.

**Comment by bitcraft** [comment]
Ok, thanks for that info.  I will look into what it will take to support chunks.

**Comment by crushedhat** [comment]
`deadnode:Game havox$ python main.py 
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    g = Game()
  File "main.py", line 18, in __init__
    self.load_data()
  File "main.py", line 24, in load_data
    self.map = TiledMap('maptest.tmx')
  File "/Users/havox/Desktop/game/Game/maps.py", line 9, in __init__
    tm = load_pygame(filename)
  File "build/bdist.macosx-10.13-intel/egg/pytmx/util_pygame.py", line 141, in load_pygame
  File "build/bdist.macosx-10.13-intel/egg/pytmx/pytmx.py", line 352, in __init__
  File "build/bdist.macosx-10.13-intel/egg/pytmx/pytmx.py", line 383, in parse_xml
  File "build/bdist.macosx-10.13-intel/egg/pytmx/pytmx.py", line 942, in __init__
  File "build/bdist.macosx-10.13-intel/egg/pytmx/pytmx.py", line 1052, in parse_xml
ValueError: invalid literal for int() with base 10: ''`

I am receiving the same error while trying to load the map. It is not infinite though. I'm using the following code which was a solution to `pytmx.load_pygame` not working properly.

`from pytmx.util_pygame import load_pygame`
`tm = load_pygame(filename)`

**Comment by Bloedprodukt** [comment]
I have the same Error, even though I am not trying to load an infinite map.
Is there already a fix for that problem or a walk I could use?

**Comment by Matombo** [comment]
When the map is encoded in base64 and not csv the error changes to:
"TypeError: 'NoneType' object is not an iterator" but happens still at the same position

**Comment by Matombo** [comment]
@Bloedprodukt you are most likely running into a different issue because this one is very clearly related to unsupported "infinite" maps

**Comment by kalortpol** [comment]
Hello!

I am wondering if there was a solution to this? I might have missed it being quite new to pygame, pytmx and python (3.x) as a whole. 

I had a working tiled map loaded with layers and all and rendered it to screen, then I changed the map in tiled (it's not infinite) by changing some tiles graphics and added more objects (only empty rects acting as blockers, which I already had in the map without problems) and the following error is now raised, which seem identical to the original one above:

  File "Python38-32\classesNYAST.py", line 89, in render_tiles_to_screen
    tmx_data = load_pygame(filename)
  File "Python38-32\lib\site-packages\pytmx\util_pygame.py", line 141, in load_pygame
    return pytmx.TiledMap(filename, *args, **kwargs)
  File "\Python38-32\lib\site-packages\pytmx\pytmx.py", line 360, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "Python38-32\lib\site-packages\pytmx\pytmx.py", line 397, in parse_xml
    self.add_layer(TiledObjectGroup(self, subnode))
  File "Python38-32\lib\site-packages\pytmx\pytmx.py", line 1096, in __init__
    self.parse_xml(node)
  File "Python38-32\lib\site-packages\pytmx\pytmx.py", line 1104, in parse_xml
    self._set_properties(node)
  File "Python38-32\lib\site-packages\pytmx\pytmx.py", line 272, in _set_properties
    self._cast_and_set_attributes_from_node_items(node.items())
  File "Python38-32\lib\site-packages\pytmx\pytmx.py", line 235, in _cast_and_set_attributes_from_node_items
    casted_value = types[key](value)
ValueError: invalid literal for int() with base 10: '5.33333'
